name: Node.js CI

jobs:
  build:
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"

      - name: install dependencies
        run: npm ci

      - name: npm run test
        run: npm test

      - name: Run build
        run: npm run build --if-present
