name: CI angular
on:
  push:
    branches:
      - main

jobs:
  build:
    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"

      - name: Install dependencies
        run: npm ci

      - name: Run tests (headless)
        run: npm test -- --browsers ChromeHeadless --single-run

      - name: Run build
        run: npm run build --if-present
